{
  "branches": ["master"],
  "plugins":
    [
      [
        "@semantic-release/commit-analyzer",
        {
          "preset": "angular",
          "releaseRules":
            [
              { "type": "refactor", "release": "patch" },
              { "type": "sync", "release": "minor" },
            ],
          "parserOpts":
            { "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES"] },
        },
      ],
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/git",
        {
          "assets": ["version.properties"],
          "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
        },
      ],
      [
        "@semantic-release/exec",
        {
          {
            "prepareCmd": "./scripts/update_version.sh ${nextRelease.version}",
          },
        },
      ],
    ],
}
