{
  "branches": ["master"],
  "plugins":
    [
      "@semantic-release/commit-analyzer",
      [
        "@semantic-release/release-notes-generator",
        {
          "preset": "conventionalcommits",
          "presetConfig":
            {
              "types":
                [
                  { type: "feat", section: "Features", hidden: false },
                  { type: "fix", section: "Bug Fixes", hidden: false },
                  {
                    type: "perf",
                    section: "Performance Improvements",
                    hidden: false,
                  },
                  { type: "revert", section: "Reverts", hidden: false },
                  { type: "docs", section: "Other Updates", hidden: false },
                  { type: "style", section: "Other Updates", hidden: false },
                  { type: "chore", section: "Other Updates", hidden: false },
                  { type: "refactor", section: "Other Updates", hidden: false },
                  { type: "test", section: "Other Updates", hidden: false },
                  { type: "build", section: "Other Updates", hidden: false },
                  { type: "ci", section: "Other Updates", hidden: false },
                  { type: "sync", section: "Other Updates", hidden: false },
                ],
            },
        },
      ],
      [
        "@semantic-release/git",
        {
          "assets": ["version.properties"],
          "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
        },
      ],
      [
        "@semantic-release/exec",
        {
          {
            "prepareCmd": "./scripts/update_version.sh ${nextRelease.version}",
          },
        },
      ],
    ],
}
