name: Reusable patch version
description: Reusable patch version

inputs:
  appId:
    required: true
    description: "App ID for committing and pushing"
  appSecret:
    description: "App secret"
    required: true

runs:
  using: composite

  steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ inputs.appId }}
        private-key: ${{ inputs.appSecret }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
        ref: master

    - name: Bump version
      shell: bash
      id: version
      run: |
        ./gradlew bumpPatchVersion --no-configuration-cache

    - name: Retrieve version
      shell: bash
      id: versionName
      env:
        FILE_PATH: ./build.gradle.kts
      run: |
        version=$(grep -E 'version\s*=\s*"[^"]+"' $FILE_PATH | head -1 | awk -F'"' '{print $2}')

        if [ -z "$version" ]; then
          echo "Error: Failed to extract version from $FILE_PATH"
          exit 1
        fi

        echo "Extracted version: $version"
        echo "versionName=$version" >> $GITHUB_ENV
        echo "versionName=$version" >> $GITHUB_OUTPUT

    - name: Commit changes
      id: committer
      uses: planetscale/ghcommit-action@v0.1.44
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      with:
        repo: ${{ github.repository }}
        branch: master
        commit_message: "chore(common): version bump to ${{ steps.versionName.outputs.versionName }}"
        file_pattern: "./build.gradle.kts"
