name: Patch version, publish to GitHubPackages and create new GitHub release

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: rees46/kmp/.github/actions/version@master
        if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
        with:
          appId: ${{ vars.PUBLIVERSIONER_ID }}
          appSecret: ${{ secrets.PUBLIVERSIONER_SECRET }}

  publish:
    needs: version
    uses: rees46/workflow/.github/workflows/reusable-android-publish.yaml@master
    permissions: write-all
    with:
      appId: ${{ vars.PUBLIVERSIONER_ID }}
      PROPERTIES_FILE: gradle.properties
      SIGNING_SECRET_KEY_RING_FILE: com.rees46.key.gpg
      SIGNING_SECRET_KEY_RING_FILE_LOCATION: ./
      OSSRH_USERNAME: ${{ vars.OSSRH_USERNAME }}
      VARIANT_NAME: ${{ vars.VARIANT_NAME }}
      URL: ${{ vars.URL }}
      MAVEN_REPOSITORY_URL: ${{ vars.MAVEN_REPOSITORY_URL }}
      GRADLE_VERSION: 8.8
    secrets:
      SONATA_STAGING_PROFILE_ID: ${{ secrets.SONATA_STAGING_PROFILE_ID }}
      appSecret: ${{ secrets.PUBLIVERSIONER_SECRET }}
      SONATA_USERNAME: ${{ secrets.SONATA_USERNAME }}
      SONATA_PASSWORD: ${{ secrets.SONATA_PASSWORD }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      SIGNING_KEY_FILE_AS_BASE64_STRING: ${{ secrets.SIGNING_KEY_FILE_AS_BASE64_STRING }}

  release:
    needs: [publish, version]
    runs-on: ubuntu-latest
    steps:
      - uses: rees46/kmp/.github/actions/release@master
        with:
          appId: ${{ vars.PUBLIVERSIONER_ID }}
          appSecret: ${{ secrets.PUBLIVERSIONER_SECRET }}
