name: Publish to sonatype and GH-packages

on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/'))
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: rees46/kmp/.github/actions/publish@33ddff7a7843107fb1667d7681ed3da27f0a0741
        if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
        with:
          appId: ${{ vars.PUBLIVERSIONER_ID }}
          appSecret: ${{ secrets.PUBLIVERSIONER_SECRET }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
